App\Entity\Project:
    collectionOperations:
        get:
            normalization_context:
                groups: ['project:collection:get']
        post:
            normalization_context:
                groups: ['project:item:get']
            denormalization_context:
                groups: ['project:collection:post']
    itemOperations: ~
