App\Entity\User:
    collectionOperations:
        register:
            method: POST
            input: App\Dto\CreateUser
            normalization_context:
                groups: ['user:item:get']
    itemOperations:
        get:
            normalization_context:
                groups: ['user:item:get']
        modify:
            method: PUT
            input: App\Dto\ModifyUser
            normalization_context:
                groups: ['user:item:get']
            security:
                'is_granted("ROLE_ADMIN") or object == user'
