App\Entity\Project:
    attributes:
        id:
          groups: ['user:item:get', 'project:item:get', 'project:item:put', 'project:collection:get']
        name: 
          groups: ['user:item:get', 'project:item:get', 'project:item:put', 'project:collection:post', 'project:item:put', 'project:collection:get']
        users:
          groups: ['project:collection:post', 'project:item:get','project:item:put', 'project:collection:get']
