App\Entity\User:
    attributes:
        id:
          groups: ['user:item:get', 'user:item:put']
        email: 
          groups: ['user:item:get', 'user:collection:post', 'user:collection:get', 'user:item:put']
        password:
          groups: ['user:collection:post', 'user:item:put']
        projects:
          groups: ['user:item:get']